namespace TicketHubDataLibrary.Migrations
{
    using System;
    using System.Data.Entity.Migrations;

    public partial class AutoGenGUID : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.ActionLogs", "UserId", "dbo.Admins");
            DropForeignKey("dbo.LoginLogs", "UserId", "dbo.Admins");
            DropForeignKey("dbo.Shops", "ReviewerId", "dbo.Admins");
            DropForeignKey("dbo.ActionLogs", "UserId", "dbo.Users");
            DropForeignKey("dbo.LoginLogs", "UserId", "dbo.Users");
            DropForeignKey("dbo.ShopEmployees", "UserId", "dbo.Users");
            DropForeignKey("dbo.Issues", "IssuerId", "dbo.Users");
            DropForeignKey("dbo.Orders", "UserId", "dbo.Users");
            DropForeignKey("dbo.Tickets", "UserId", "dbo.Users");
            DropForeignKey("dbo.UserLogins", "UserId", "dbo.Users");
            DropForeignKey("dbo.UserRoles", "UserId", "dbo.Users");
            DropForeignKey("dbo.Refunds", "UserId", "dbo.Users");
            DropForeignKey("dbo.UserFavoriteShops", "UserId", "dbo.Users");
            DropForeignKey("dbo.UserWishIssues", "UserId", "dbo.Users");
            DropForeignKey("dbo.RefundDetails", "TicketId", "dbo.Tickets");
            DropForeignKey("dbo.IssueTags", "IssueId", "dbo.Issues");
            DropForeignKey("dbo.Tickets", "IssueId", "dbo.Issues");
            DropForeignKey("dbo.OrderDetails", "IssueId", "dbo.Issues");
            DropForeignKey("dbo.UserWishIssues", "IssueId", "dbo.Issues");
            DropForeignKey("dbo.IssueTags", "TagId", "dbo.Tags");
            DropForeignKey("dbo.ShopTags", "TagId", "dbo.Tags");
            DropForeignKey("dbo.ShopEmployees", "ShopId", "dbo.Shops");
            DropForeignKey("dbo.ShopTags", "ShopId", "dbo.Shops");
            DropForeignKey("dbo.Issues", "ShopId", "dbo.Shops");
            DropForeignKey("dbo.UserFavoriteShops", "ShopId", "dbo.Shops");
            DropForeignKey("dbo.OrderDetails", "OrderId", "dbo.Orders");
            DropForeignKey("dbo.Tickets", "OrderId", "dbo.Orders");
            DropForeignKey("dbo.UserRoles", "RoleId", "dbo.Roles");
            DropForeignKey("dbo.RefundDetails", "RefundId", "dbo.Refunds");
            DropPrimaryKey("dbo.ActionLogs");
            DropPrimaryKey("dbo.Admins");
            DropPrimaryKey("dbo.LoginLogs");
            DropPrimaryKey("dbo.Users");
            DropPrimaryKey("dbo.Tickets");
            DropPrimaryKey("dbo.Issues");
            DropPrimaryKey("dbo.Tags");
            DropPrimaryKey("dbo.Shops");
            DropPrimaryKey("dbo.Orders");
            DropPrimaryKey("dbo.Roles");
            DropPrimaryKey("dbo.Refunds");
            AlterColumn("dbo.ActionLogs", "Id", c => c.Guid(nullable: false, identity: true, defaultValueSql: "newid()"));
            AlterColumn("dbo.Admins", "Id", c => c.Guid(nullable: false, identity: true, defaultValueSql: "newid()"));
            AlterColumn("dbo.LoginLogs", "Id", c => c.Guid(nullable: false, identity: true, defaultValueSql: "newid()"));
            AlterColumn("dbo.Users", "Id", c => c.Guid(nullable: false, identity: true, defaultValueSql: "newid()"));
            AlterColumn("dbo.Tickets", "Id", c => c.Guid(nullable: false, identity: true, defaultValueSql: "newid()"));
            AlterColumn("dbo.Issues", "Id", c => c.Guid(nullable: false, identity: true, defaultValueSql: "newid()"));
            AlterColumn("dbo.Tags", "Id", c => c.Guid(nullable: false, identity: true, defaultValueSql: "newid()"));
            AlterColumn("dbo.Shops", "Id", c => c.Guid(nullable: false, identity: true, defaultValueSql: "newid()"));
            AlterColumn("dbo.Orders", "Id", c => c.Guid(nullable: false, identity: true, defaultValueSql: "newid()"));
            AlterColumn("dbo.Roles", "Id", c => c.Guid(nullable: false, identity: true, defaultValueSql: "newid()"));
            AlterColumn("dbo.Refunds", "Id", c => c.Guid(nullable: false, identity: true, defaultValueSql: "newid()"));
            AddPrimaryKey("dbo.ActionLogs", "Id");
            AddPrimaryKey("dbo.Admins", "Id");
            AddPrimaryKey("dbo.LoginLogs", "Id");
            AddPrimaryKey("dbo.Users", "Id");
            AddPrimaryKey("dbo.Tickets", "Id");
            AddPrimaryKey("dbo.Issues", "Id");
            AddPrimaryKey("dbo.Tags", "Id");
            AddPrimaryKey("dbo.Shops", "Id");
            AddPrimaryKey("dbo.Orders", "Id");
            AddPrimaryKey("dbo.Roles", "Id");
            AddPrimaryKey("dbo.Refunds", "Id");
            AddForeignKey("dbo.ActionLogs", "UserId", "dbo.Admins", "Id", cascadeDelete: true);
            AddForeignKey("dbo.LoginLogs", "UserId", "dbo.Admins", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Shops", "ReviewerId", "dbo.Admins", "Id");
            AddForeignKey("dbo.ActionLogs", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.LoginLogs", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ShopEmployees", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Issues", "IssuerId", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Orders", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Tickets", "UserId", "dbo.Users", "Id");
            AddForeignKey("dbo.UserLogins", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.UserRoles", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Refunds", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.UserFavoriteShops", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.UserWishIssues", "UserId", "dbo.Users", "Id");
            AddForeignKey("dbo.RefundDetails", "TicketId", "dbo.Tickets", "Id");
            AddForeignKey("dbo.IssueTags", "IssueId", "dbo.Issues", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Tickets", "IssueId", "dbo.Issues", "Id");
            AddForeignKey("dbo.OrderDetails", "IssueId", "dbo.Issues", "Id");
            AddForeignKey("dbo.UserWishIssues", "IssueId", "dbo.Issues", "Id");
            AddForeignKey("dbo.IssueTags", "TagId", "dbo.Tags", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ShopTags", "TagId", "dbo.Tags", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ShopEmployees", "ShopId", "dbo.Shops", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ShopTags", "ShopId", "dbo.Shops", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Issues", "ShopId", "dbo.Shops", "Id", cascadeDelete: true);
            AddForeignKey("dbo.UserFavoriteShops", "ShopId", "dbo.Shops", "Id", cascadeDelete: true);
            AddForeignKey("dbo.OrderDetails", "OrderId", "dbo.Orders", "Id");
            AddForeignKey("dbo.Tickets", "OrderId", "dbo.Orders", "Id");
            AddForeignKey("dbo.UserRoles", "RoleId", "dbo.Roles", "Id", cascadeDelete: true);
            AddForeignKey("dbo.RefundDetails", "RefundId", "dbo.Refunds", "Id");
        }

        public override void Down()
        {
            DropForeignKey("dbo.RefundDetails", "RefundId", "dbo.Refunds");
            DropForeignKey("dbo.UserRoles", "RoleId", "dbo.Roles");
            DropForeignKey("dbo.Tickets", "OrderId", "dbo.Orders");
            DropForeignKey("dbo.OrderDetails", "OrderId", "dbo.Orders");
            DropForeignKey("dbo.UserFavoriteShops", "ShopId", "dbo.Shops");
            DropForeignKey("dbo.Issues", "ShopId", "dbo.Shops");
            DropForeignKey("dbo.ShopTags", "ShopId", "dbo.Shops");
            DropForeignKey("dbo.ShopEmployees", "ShopId", "dbo.Shops");
            DropForeignKey("dbo.ShopTags", "TagId", "dbo.Tags");
            DropForeignKey("dbo.IssueTags", "TagId", "dbo.Tags");
            DropForeignKey("dbo.UserWishIssues", "IssueId", "dbo.Issues");
            DropForeignKey("dbo.OrderDetails", "IssueId", "dbo.Issues");
            DropForeignKey("dbo.Tickets", "IssueId", "dbo.Issues");
            DropForeignKey("dbo.IssueTags", "IssueId", "dbo.Issues");
            DropForeignKey("dbo.RefundDetails", "TicketId", "dbo.Tickets");
            DropForeignKey("dbo.UserWishIssues", "UserId", "dbo.Users");
            DropForeignKey("dbo.UserFavoriteShops", "UserId", "dbo.Users");
            DropForeignKey("dbo.Refunds", "UserId", "dbo.Users");
            DropForeignKey("dbo.UserRoles", "UserId", "dbo.Users");
            DropForeignKey("dbo.UserLogins", "UserId", "dbo.Users");
            DropForeignKey("dbo.Tickets", "UserId", "dbo.Users");
            DropForeignKey("dbo.Orders", "UserId", "dbo.Users");
            DropForeignKey("dbo.Issues", "IssuerId", "dbo.Users");
            DropForeignKey("dbo.ShopEmployees", "UserId", "dbo.Users");
            DropForeignKey("dbo.LoginLogs", "UserId", "dbo.Users");
            DropForeignKey("dbo.ActionLogs", "UserId", "dbo.Users");
            DropForeignKey("dbo.Shops", "ReviewerId", "dbo.Admins");
            DropForeignKey("dbo.LoginLogs", "UserId", "dbo.Admins");
            DropForeignKey("dbo.ActionLogs", "UserId", "dbo.Admins");
            DropPrimaryKey("dbo.Refunds");
            DropPrimaryKey("dbo.Roles");
            DropPrimaryKey("dbo.Orders");
            DropPrimaryKey("dbo.Shops");
            DropPrimaryKey("dbo.Tags");
            DropPrimaryKey("dbo.Issues");
            DropPrimaryKey("dbo.Tickets");
            DropPrimaryKey("dbo.Users");
            DropPrimaryKey("dbo.LoginLogs");
            DropPrimaryKey("dbo.Admins");
            DropPrimaryKey("dbo.ActionLogs");
            AlterColumn("dbo.Refunds", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Roles", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Orders", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Shops", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Tags", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Issues", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Tickets", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Users", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.LoginLogs", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Admins", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.ActionLogs", "Id", c => c.Guid(nullable: false));
            AddPrimaryKey("dbo.Refunds", "Id");
            AddPrimaryKey("dbo.Roles", "Id");
            AddPrimaryKey("dbo.Orders", "Id");
            AddPrimaryKey("dbo.Shops", "Id");
            AddPrimaryKey("dbo.Tags", "Id");
            AddPrimaryKey("dbo.Issues", "Id");
            AddPrimaryKey("dbo.Tickets", "Id");
            AddPrimaryKey("dbo.Users", "Id");
            AddPrimaryKey("dbo.LoginLogs", "Id");
            AddPrimaryKey("dbo.Admins", "Id");
            AddPrimaryKey("dbo.ActionLogs", "Id");
            AddForeignKey("dbo.RefundDetails", "RefundId", "dbo.Refunds", "Id");
            AddForeignKey("dbo.UserRoles", "RoleId", "dbo.Roles", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Tickets", "OrderId", "dbo.Orders", "Id");
            AddForeignKey("dbo.OrderDetails", "OrderId", "dbo.Orders", "Id");
            AddForeignKey("dbo.UserFavoriteShops", "ShopId", "dbo.Shops", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Issues", "ShopId", "dbo.Shops", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ShopTags", "ShopId", "dbo.Shops", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ShopEmployees", "ShopId", "dbo.Shops", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ShopTags", "TagId", "dbo.Tags", "Id", cascadeDelete: true);
            AddForeignKey("dbo.IssueTags", "TagId", "dbo.Tags", "Id", cascadeDelete: true);
            AddForeignKey("dbo.UserWishIssues", "IssueId", "dbo.Issues", "Id");
            AddForeignKey("dbo.OrderDetails", "IssueId", "dbo.Issues", "Id");
            AddForeignKey("dbo.Tickets", "IssueId", "dbo.Issues", "Id");
            AddForeignKey("dbo.IssueTags", "IssueId", "dbo.Issues", "Id", cascadeDelete: true);
            AddForeignKey("dbo.RefundDetails", "TicketId", "dbo.Tickets", "Id");
            AddForeignKey("dbo.UserWishIssues", "UserId", "dbo.Users", "Id");
            AddForeignKey("dbo.UserFavoriteShops", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Refunds", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.UserRoles", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.UserLogins", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Tickets", "UserId", "dbo.Users", "Id");
            AddForeignKey("dbo.Orders", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Issues", "IssuerId", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ShopEmployees", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.LoginLogs", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ActionLogs", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Shops", "ReviewerId", "dbo.Admins", "Id");
            AddForeignKey("dbo.LoginLogs", "UserId", "dbo.Admins", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ActionLogs", "UserId", "dbo.Admins", "Id", cascadeDelete: true);
        }
    }
}
